### Exercice 1:

Write a function that takes a string, and two indexes (integers), and returns a slice of that string as well as the length of the string.
Call the function, and store the results in two variables

In [8]:
def slice2str(a,b,c):
    if(b<c):
        return a[b:c+1]
    else:
        return a[c:b+1]

slice2str("hello world",2,7)

'llo wo'

### Exercice 2:

1. Write a function that takes two arguments, and returns the sum of the two.
2. Call the function with the values 1 and 2.1, then check the type of the result.
3. Call the function with the values False and 2, then check the type of the result.

In [11]:
def sum(m,n):
    return m+n
print(sum(1,2.1))
type(sum(1,2.1))
print(sum(False,2))
type(sum(False,2))

3.1
2


int

### Exercice 3:

Write a function that takes a string and returns a dictionary containing character frequency.

*example*

    string sample: 'test'
    
    expected result: {'t':2, 'e':1, 's':1}

In [12]:
def dictionary(string):
    Dict = {}
    for i in string:
        if i in Dict:
            Dict[i] += 1
        else:
            Dict[i] = 1
    print (Dict)

dictionary('test')

{'t': 2, 'e': 1, 's': 1}


### Exercice 4:

Given two lists, iterate both lists simultaniously, such the first list would display item in original order and the second list in reverse order

*example*:

In [3]:
from lib import print_orl #this is a lib you dont have access to
print_orl([1,2,3],[1,2,3])

1 3
2 2
3 1


In [14]:
def reverse(L):
    n=len(L)
    for i in range (0,n):
        print (L[i],'',L[n-i-1])
reverse([1,2,3])

1  3
2  2
3  1


### Exercice 5:

Given two 2d arrays, stack them horizontally.

*example:*

In [15]:
import numpy as np
#The input
a = np.ones((1, 10)).reshape(2, -1)
b = np.zeros((1, 10)).reshape(2, -1)
#Try to print input
print(a)
print(b)
#concatenate horizontally
def concat(a,b):
    C=np.zeros((1,20)).reshape(2,-1)
    k=0
    for i in range(5):
        C[k][i]=a[k][i]
        C[k][i+5]=b[k][i]
    k=1
    for j in range(5):
        C[k][j]=a[k][j]
        C[k][j+5]=b[k][j]
    return C
concat(a,b)



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])

### exercice 6:

Create the following patterns using the bellow arrays a and b, and numpy functions:

In [17]:
import numpy as np
a = np.arange(3)
b = np.ones((3,3,3))
print(a)
print(b)
print('output1')
c=[]
for i in range(3):
    c.append(0)
for i in range(3):
    c.append(1)
for i in range(3):
    c.append(2)
for i in range (3):
    for k in range(3):
        c.append(a[k])     
print(c)
print('output2')
d=np.ones((3,3,3))
for i in range (3):
    for j in range(3):
        k = 1
        d[i][j][k] = d[i][j][k] + 1
        k = 2
        d[i][j][k] = d[i][j][k] + 2
print(d)
print('output3')
b=b.reshape(3,9)
print(b)


[0 1 2]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
output1
[0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]
output2
[[[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]]
output3
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
